"""Typed, mutation-free boundary for future per-session Quick Demo runtimes."""
from __future__ import annotations
from typing import Protocol
from app.models import QuickDemoSession

STATES = (
    "requested", "allocating_runtime", "creating_database", "copying_filestore",
    "creating_user", "binding_route", "health_check", "active", "expired",
    "cleaning", "deleted", "failed",
)
PROVISIONING_STATES = STATES[:7]
TERMINAL_STATES = frozenset({"active", "expired", "deleted", "failed"})

class QuickDemoRuntime(Protocol):
    name: str
    version: str
    def allocate_slot(self, session: QuickDemoSession) -> dict[str, str]: ...
    def create_role(self, session: QuickDemoSession) -> dict[str, str]: ...
    def clone_database(self, session: QuickDemoSession) -> dict[str, str]: ...
    def copy_filestore(self, session: QuickDemoSession) -> dict[str, str]: ...
    def create_restricted_user(self, session: QuickDemoSession) -> dict[str, str]: ...
    def prepare_configuration(self, session: QuickDemoSession) -> dict[str, str]: ...
    def create_runtime(self, session: QuickDemoSession) -> dict[str, str]: ...
    def bind_route(self, session: QuickDemoSession) -> dict[str, str]: ...
    def health_check(self, session: QuickDemoSession) -> dict[str, str]: ...
    def expire(self, session: QuickDemoSession) -> None: ...
    def reconcile(self, session: QuickDemoSession) -> dict[str, str]: ...
    def cleanup_owned_artifacts(self, session: QuickDemoSession) -> None: ...
